.TH VIEWER 1 "July 21 2002"
.SH NAME
viewer \- stereo pair viewer/aligner
.SH SYNOPSIS
.B viewer
[
.I options
]
[
.I file(s)
]

.B viewer
[
.I basename
]
.LP
.SH DESCRIPTION
.LP
.B viewer
is an OpenGL based stereo pair viewer and aligner. At present it only 
accepts images in the PPM image format but work is in progress to allow 
use of other image types.
.B viewer
is known to work on various systems, including Linux and OSX, but should 
work on anything with OpenGL and a compiler. Besides being useful as a 
stereo pair viewer it is also possible to view a mono image and easliy 
pan/drag around within the image.

There are three modes in which to use
.B viewer
: as a mono viewer (with the
.B
-m
option), as a stereo viewer (with the
.B
-i
or
.B
-v
option), or as a stereo pair aligner (with the
.B
-a
option). There is an additional special way that
.B
viewer
can be run: if no arguments are given and only an image 'basename' is 
given the program will load basename-l.ppm and basename-r.ppm and enter 
viewer mode. This can be very convenient for viewing already aligned 
image pairs using the default configuration. If the program is not run 
in with a basename then one of the
.B
-m
,
.B
-v
,
.B
-i
, or
.B
-a
options must be used. The
.B
-o
,
.B
-l
, and
.B
-r
options are only useful when running in aligner mode. If
.B
viewer
is run using basename it enters aligner mode.

Additionally it is possible to pass the
.B
-g
option to specify the window size. If this option is omitted then the 
window will cover the entire desktop.

Depending upon which mode the program is running in the cursor keys will 
vary. In viewer mode it is assumed that both images will be moved 
together and that not much 'fine tuning' will be necessary, so by 
default movement is over the image in the specified direction in 
increments of 10 pixels. If
.B
SHIFT
is used in combination with cursor keys then movement will be in
increments of 1 pixel. In addition, the user can press
.B
a
to temporarily enter 'fine alignment' mode. In this mode the cursor key 
behavior acts as if the program were in aligner mode until this key is 
hit again to return to the standard viewer behaviour.

The keyboard behavior of mono viewer mode is identical to standard 
viewer mode with the exception that there is no fine alignment mode.

In alignment mode the cursor key interaction is slightly more 
complicated due to the extra flexibility necessary. It is known that 
some window managers (notably KDE) will intercept some of these keyboard 
commands. The user may wish to redefine the behaviour of the window 
manager to avoid this. Future plans for
.B
viewer
include the ability to use user-defined keyboard commands to avoid this 
problem.

The mouse can be used to drag images in all viewer modes. In alignment 
mode left clicking and dragging will move the particular image (left or 
right), whereas middle clicking and dragging will move both images. In 
viewer and mono modes clicking either the left or middle button and 
dragging will move both images.

.SH OPTIONS
The options are:
.TP
.BI \-h,\ --help
Display usage and version information and exit
.TP
.BI \-i,\ --input \ [leftimage.ppm\ rightimage.ppm]
Display a pair of images in viewer mode
.TP
.BI \-v,\ --view \ [fullimage.ppm]
Display a combined pair of images in viewer mode. assumes left half of 
image is left eye image and right half of image is right eye image.
.TP
.BI \-m,\ --mono \ [monoimage.ppm]
Display a mono image in viewer mode
.TP
.BI \-a,\ --align \ [leftinfile.ppm\ rightinfile.ppm]
Display a pair of images in aligner mode
.TP
.BI \-o,\ --output \ [fulloutfile.ppm]
Specify the output file for a joined stereo pair. Default value is 
fullout.ppm. This option is only useful in aligner mode.
.TP
.BI \-l,\ --left \ [leftoutfile.ppm]
Specify the output file for the left half of a stereo pair. Default
value is leftout.ppm. This option is only useful in aligner mode.
.TP
.BI \-r,\ --right \ [rightoutfile.ppm]
Specify the output file for the right half of a stereo pair. Default
value is rightout.ppm. This option is only useful in aligner mode.
.TP
.BI \-g,\ --geom \ [WIDTH]x[HEIGHT]
Forces viewer to use a specified window geometry. The default 
behavior is to cover the entire desktop.
.TP
.BI \-x,\ --off \ [x_offset][y_offset]
Specifies the offset of the right hand image relative to the left hand 
image. this option should only be used AFTER a filename has been 
specified on teh command line (ie: viewer -i left.ppm right.ppm -x 
-2+4).
.TP
.BI \-n,\ --nothumb
Disables thumbnail view
.TP
.BI \-f,\ --file \ [filename]
Specifies a file which contains a list with four entries per line, the 
first representing the filename of the left hand image, the second 
representing the filename of the right hand image, the third 
representing the x offset of the right image and the fourth representing 
the y offset of the right image. The 'n' (or next) and 'p' (or prev) 
keys can be used to view multiple pairs as a slideshow.

.SH viewer mode commands
these are the commands available while in viewer mode:
.TP
.BI q,\ ESC
quit
.TP
.BI a
toggle 'fine alignment' mode on/off. this will cause the cursor keys to 
temporarily act as in aligner mode.
.TP
.BI x
zoom out
.TP
.BI z
zoom in
.TP
.BI n
next image
.TP
.BI p
previous image
.TP
.BI c
center images
.TP
.BI LEFT
move left over image by 10 pixels
.TP
.BI SHIFT+LEFT
move left over image by 1 pixel
.TP
.BI RIGHT
move right over image by 10 pixels
.TP
.BI SHIFT+RIGHT
move right over image by 1 pixel
.TP
.BI UP
move up over image by 10 pixels
.TP
.BI SHIFT+UP
move up over image by 1 pixel
.TP
.BI DOWN
move down over image by 10 pixels
.TP
.BI SHIFT+DOWN
move down over image by 1 pixel

.SH mono viewer mode commands
the commands for mono viewer mode are identical to standard viewer mode, 
however there is no fine alignment since there is only a single image.

.SH aligner mode commands
these are the commands available in aligner mode:
.TP
.BI q,\ ESC
quit
.TP
.BI n
next image
.TP
.BI p
previous image
.TP
.BI ENTER
crop images to screen and write left, right, and joined images
.TP
.BI SHIFT+ENTER
crop images to screen and write left, right, and joined images, then 
immediately exit
.TP
.BI LEFT,\ RIGHT,\ UP,\ DOWN
move left image 1 pixel in specified direction
.TP
.BI CTRL+(LEFT,\ RIGHT,\ UP,\ DOWN)
move left image 10 pixels in specified direction
.TP
.BI SHIFT+(LEFT,\ RIGHT,\ UP,\ DOWN)
move right image 1 pixel in specified direction
.TP
.BI SHIFT+CTRL+(LEFT,\ RIGHT,\ UP,\ DOWN)
move right image 10 pixels in specified direction
.TP
.BI ALT+(LEFT,\ RIGHT,\ UP,\ DOWN)
move both images 1 pixel in specified direction
.TP
.BI ALT+CTRL+(LEFT,\ RIGHT,\ UP,\ DOWN)
move both images 10 pixels in specified direction

.SH EXAMPLES
	viewer pair0611b

will read pair0611b-l.ppm as the left image and pair0611b-r.ppm as the
right image. when the image is cropped (by pressing enter) the files
pair0611b-leftcrop.ppm, pair0611b-rightcrop.ppm, and pair0611b-pair.ppm
will be written.

	viewer -a pair0611b-l.ppm pair0611b-r.ppm

is equivalent to the above command in that it will read the same two
files, however the default output filenames will be leftout.ppm,        
rightout.ppm, and fullout.ppm rather than the above.

	viewer -a pair0611b-l.ppm pair0611b-r.ppm -l cropleft.ppm -r cropright.ppm -o stereoimage.ppm

this again reads the same two images, however rather than using the
default output filenames it will write the cropped and stereo images to
the specified filenames. if any of the output options are omitted the   
default will be used.

	viewer -v pair0611b-pair.ppm

this will simply allow you to view the cropped and aligned stereo pair
which was created in the first example above.

	viewer -m monoimage.ppm

this will read a single image in mono viewer mode.

	viewer -i lefty.ppm righty.ppm -g 1024x384

will load the specified pair in viewer mode in a window covering the
upper half of a 1024x768 desktop.

	viewer -i left1.ppm right1.ppm -off +3-5 --input left2.ppm right2.ppm -i left3.ppm right3.ppm -x -3+0

this will load a series of three images for a slideshow. the first and 
third are not quite aligned so an offset is speciified, but the second 
pair is already aligned so no offset information is necessary. note that 
the offset option applies to the PREVIOUS file input option.

	viewer -f slideshow

this will load a series of images with the filenames and offets being 
taken from the file. each line of the file should contain exactly four 
items: left image name, right image name, x offset, y offset. these 
items are separated by spaces and all four options must be present. 
comments may be inserted into the file for better readability by using a 
# sign at the start of a line. blank lines will also be ignored.

.SH ENVIRONMENT
.TP
No special environment variables.
.SH LICENSE
This software is covered under the GNU Public License as outlined in the
COPYING file included with this distribution.
.SH AUTHORS
Russ Burdick <wburdick@cs.umn.edu>, with contributions from Nathan Weeks 
<weeks@usgs.gov>.
.SH BUGS
No known bugs at this time. Please send bug reports to the author.
.PP
